language: python
notifications:
  irc:
    - "irc.freenode.net#suplemon"
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - "pip install -r requirements-dev.txt"

# command to run tests
script:
  - "./test.sh"
